Unit4/Models/book.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Unit4.Models
{
    public class book
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string info { get; set; }
        public int price { get; set; }
        public string discount { get; set; }

        [BindProperty, DataType(DataType.Date)]
        public DateTime pubdate { get; set; }
        public int category { get; set; }
        public int bookquantity { get; set; }
        public string imgfile { get; set; }
    }

}

Unit4/Models/orderdetail.cs
namespace Unit4.Models
{
    public class orderdetail
    {
        public int Id { get; set; }
        public string customer { get; set; }
        public string booktitle { get; set; }
        public int quantity { get; set; }

    }
}

Unit4/Controllers/bookController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Unit4.Models;

namespace Unit4.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class bookController : ControllerBase //Name on dr.aiman: "apibookController"
    {
        // getting all book search catagory
        [HttpGet("{cat}")]
        public IEnumerable<book> Get(int cat)
        {
            List<book> li = new List<book>();
            //  SqlConnection conn1 = new SqlConnection("Data Source=.\\sqlexpress;Initial Catalog=mynewdb;Integrated Security=True;Pooling=False");
            var builder = WebApplication.CreateBuilder();
            string conStr = builder.Configuration.GetConnectionString("Unit4Context");
            SqlConnection conn1 = new SqlConnection(conStr);
            string sql;
            sql = "SELECT * FROM book where category ='" + cat + "' ";
            SqlCommand comm = new SqlCommand(sql, conn1);
            conn1.Open();
            SqlDataReader reader = comm.ExecuteReader();

            while (reader.Read())
            {
                li.Add(new book
                {
                    title = (string)reader["title"],
                });

            }

            reader.Close();
            conn1.Close();
            return li;
        }




    }

}

Unit4/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Unit4.Data;
using Unit4.Models;

namespace Unit4.Controllers
{
    public class booksController : Controller
    {
        private readonly Unit4Context _context;

        public booksController(Unit4Context context)
        {
            _context = context;
        }

        // GET: books
        public async Task<IActionResult> Index()
        {
              return _context.book != null ? 
                          View(await _context.book.ToListAsync()) :
                          Problem("Entity set 'Unit4Context.book'  is null.");
        }

        public async Task<IActionResult> Catelog()
        {
            return _context.book != null ?
                        View(await _context.book.ToListAsync()) :
                        Problem("Entity set 'Unit4Context.book'  is null.");
        }

        // GET: books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: books/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IFormFile file, [Bind("Id,title,info,price,discount,pubdate,category,bookquantity")] book book)
        {
            {
                if (file != null)
                {
                    string filename = file.FileName;
                    //  string  ext = Path.GetExtension(file.FileName);
                    string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                    using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                    { await file.CopyToAsync(filestream); }

                    book.imgfile = filename;
                }

                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }


        // GET: books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, int id, [Bind("Id,title,info,price,discount,pubdate,category,bookquantity,imgfile")] book book)
        {
            if (id != book.Id)
            { return NotFound(); }

            if (file != null)
            {
                string filename = file.FileName;
                //  string  ext = Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images"));
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                { await file.CopyToAsync(filestream); }

                book.imgfile = filename;
            }
            _context.Update(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.book == null)
            {
                return NotFound();
            }

            var book = await _context.book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.book == null)
            {
                return Problem("Entity set 'Unit4Context.book'  is null.");
            }
            var book = await _context.book.FindAsync(id);
            if (book != null)
            {
                _context.book.Remove(book);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> search()
        {
            List<book> brBook = new List<book>();

            return View(brBook);

        }

        // POST: book/search
        [HttpPost]
        public async Task<IActionResult> search(string s)
        {
            var brBook = await _context.book.FromSqlRaw("select * from book where title LIKE '%" + s + "%' ").ToListAsync();
            return View(brBook);
        }


        

        public async Task<IActionResult> searchall()
        {

            {
                book brItem = new book();

                return View(brItem);
            }
        }

        [HttpPost]

        public async Task<IActionResult> SearchAll(string tit)
        {
            var bkItems = await _context.book.FromSqlRaw("select * from book where title = '" + tit + "' ").FirstOrDefaultAsync();

            return View(bkItems);
        }


        public async Task<IActionResult> orderdetail()
        {

            return View();

        }

        public async Task<IActionResult> orderdetails()
        {
            var orBooks = await _context.orderdetail.FromSqlRaw("select orders.Id as id, name as customer, title as booktitle, orders.quantity as quantity from book, orders, usersaccounts  where book.id = orders.bookid and orders.custid = usersaccounts.id  ").ToListAsync();
            return View(orBooks);
        }





        private bool bookExists(int id)
        {
          return (_context.book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Unit4/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Unit4.Data;
using Unit4.Models;

namespace Unit4.Controllers
{
    public class ordersController : Controller
    {
        private readonly Unit4Context _context;

        public ordersController(Unit4Context context)
        {
            _context = context;
        }

        // GET: orders
        public async Task<IActionResult> Index()
        {
            ViewData["role"] = HttpContext.Session.GetString("Role");
            return _context.orders != null ? 
                          View(await _context.orders.ToListAsync()) :
                          Problem("Entity set 'Unit4Context.orders'  is null.");
        }

        // GET: orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // GET: orders/Buy
        public async Task<IActionResult> Buy(int? id)
        {
                string ss = HttpContext.Session.GetString("Role");
                if (ss == "customer")
                    return View();
                else
                    return RedirectToAction("login", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Buy(int bookId, int quantity)
        {
            orders order = new orders();
            order.bookid = bookId;
            order.quantity = quantity;
            order.custid = Convert.ToInt32(HttpContext.Session.GetString("userid"));
            order.buydate = DateTime.Today;
            var builder = WebApplication.CreateBuilder();
            string conStr = builder.Configuration.GetConnectionString("Unit4Context");
            SqlConnection conn = new SqlConnection(conStr);
            string sql;
            int qt = 0;
            sql = "select * from book where (id ='" + order.bookid + "' )";
            SqlCommand comm = new SqlCommand(sql, conn);
            conn.Open();
            SqlDataReader reader = comm.ExecuteReader();
            if (reader.Read())
            {
                qt = (int)reader["bookquantity"]; // store quantity
            }
            reader.Close();
            conn.Close();
            if (order.quantity > qt)
            {
                ViewData["message"] = "maxiumam order quantity sould be " + qt;
                var book = await _context.book.FindAsync(bookId);
                return View(book);
            }
            else
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                sql = "UPDATE book  SET bookquantity  = bookquantity   - '" + order.quantity + "'  where (id ='" + order.bookid + "' )";
                comm = new SqlCommand(sql, conn);
                conn.Open();
                comm.ExecuteNonQuery();
                conn.Close();
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,bookid,custid,quantity,buydate")] orders orders)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orders);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders.FindAsync(id);
            if (orders == null)
            {
                return NotFound();
            }
            return View(orders);
        }

        // POST: orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,bookid,custid,quantity,buydate")] orders orders)
        {
            if (id != orders.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orders);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ordersExists(orders.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(orders);
        }

        // GET: orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.orders == null)
            {
                return NotFound();
            }

            var orders = await _context.orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orders == null)
            {
                return NotFound();
            }

            return View(orders);
        }

        // POST: orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.orders == null)
            {
                return Problem("Entity set 'Unit4Context.orders'  is null.");
            }
            var orders = await _context.orders.FindAsync(id);
            if (orders != null)
            {
                _context.orders.Remove(orders);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ordersExists(int id)
        {
          return (_context.orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Unit4/Views/books/Catelog.cshtml
@model IEnumerable<Unit4.Models.book>
<div class="container-fluid">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        @item.title
                    </div>
                    <div class="card-body">
                        <img src="~/images/@item.imgfile" height="150"/>
                    </div>
                    <div class="card-footer">
                        <div class="card-footer">
                            <a asp-controller="orders" asp-action="Buy" asp-route-id="@item.Id">Buy</a>
                        </div>
                        |
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Unit4/Views/books/Create.cshtml
@model Unit4.Models.book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="info" class="control-label"></label>
                <input asp-for="info" class="form-control" />
                <span asp-validation-for="info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="discount" class="control-label"></label>
                <div class="checkbox">
                    <label> <input type="radio" asp-for="discount" value="yes"/> Yes</label>
                </div>
                <div class="checkbox">
                    <label> <input type="radio" asp-for="discount" value="no"/>No</label>
                </div>
                <span asp-validation-for="discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pubdate" class="control-label"></label>
                <input asp-for="pubdate" class="form-control" />
                <span asp-validation-for="pubdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Catagory</label>
                <select class="form-control" asp-for="category">
                    <option value="0">Please select</option>
                    <option value="1">CS</option>
                    <option value="2">IS</option>
                </select>
                <span asp-validation-for="category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bookquantity" class="control-label"></label>
                <input asp-for="bookquantity" class="form-control" />
                <span asp-validation-for="bookquantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Pic</label>
                <input type="file" class="form-control" name="file" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Unit4/Views/books/Delete.cshtml
@model Unit4.Models.book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.info)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pubdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pubdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bookquantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bookquantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imgfile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imgfile)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Unit4/Views/books/Details.cshtml
@model Unit4.Models.book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.info)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pubdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pubdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.bookquantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.bookquantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imgfile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imgfile)
        </dd>
        <dt>
            Pic
        </dt>
        <dd>
            <img src="~/images/@Model.imgfile" height="150" />
            <br />@Model.imgfile

        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Unit4/Views/books/Edit.cshtml
@model Unit4.Models.book

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="info" class="control-label"></label>
                <input asp-for="info" class="form-control" />
                <span asp-validation-for="info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="discount" class="control-label"></label>
                <div class="checkbox">
                    <label> <input type="radio" asp-for="discount" value="yes" /> Yes</label>
                </div>
                <div class="checkbox">
                    <label> <input type="radio" asp-for="discount" value="no" />No</label>
                </div>
                <span asp-validation-for="discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pubdate" class="control-label"></label>
                <input asp-for="pubdate" class="form-control" />
                <span asp-validation-for="pubdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Catagory</label>
                <select class="form-control" asp-for="category">
                    <option value="0">Please select</option>
                    <option value="1">CS</option>
                    <option value="2">IS</option>
                </select>
                <span asp-validation-for="category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bookquantity" class="control-label"></label>
                <input asp-for="bookquantity" class="form-control" />
                <span asp-validation-for="bookquantity" class="text-danger"></span>
            </div>
            <img src="~/images/@Model.imgfile" height="150" />
            <div class="form-group">
                <label asp-for="imgfile" class="control-label"></label>
                <input asp-for="imgfile" class="form-control" />
                <label class="control-label">Pic</label>
                <input type="file" class="form-control" name="file" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Unit4/Views/books/Index.cshtml
@model IEnumerable<Unit4.Models.book>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<div id="myCarousel" style="width:30% ; min-width:300px " class="carousel slide mx-auto" data-ride="carousel">
    <div class="carousel-inner" id="demo">
        @{
            var counter = 0;
        }
        @foreach (var item in Model)
        {
            <div class='carousel-item   @(counter == 0 ? "active"  : String.Empty)'>
                <center> <img src="~/images/@item.imgfile" height="150"> </center>
                <div class='carousel-caption mx-auto' style='top:45%; left:15%;'>
                    <h3 style='width:100px' class='mx-auto bg-secondary  text-white'>  @item.price SR  </h3>
                    <h6 style='width:100px' class='mx-auto bg-light  text-white'>  <a asp-action="Details" asp-route-id="@item.Id">Details</a>  </h6>

                </div>
            </div>
            counter++;
        }
    </div>
    <a class="carousel-control-prev " href="#myCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon bg-secondary"></span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" data-slide="next">
        <span class="carousel-control-next-icon bg-secondary"></span>
    </a>
</div>

Unit4/Views/books/orderdetail.cshtml
@model IEnumerable<Unit4.Models.orderdetail>
@{
    ViewData["Title"] = "orderdetail";
}
<h2>orderdetail</h2>
<table class="table">
    <thead>
        <tr>
            <th> Order Id </th>
            <th>Customer Name </th>
            <th>Book Name </th>
            <th>Book Bought Quantity</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>  @Html.DisplayFor(modelItem => item.Id) </td>
                <td>  @Html.DisplayFor(modelItem => item.customer) </td>
                <td>  @Html.DisplayFor(modelItem => item.booktitle) </td>
                <td>  @Html.DisplayFor(modelItem => item.quantity)  </td>
                <td>
                    <a asp-controller="orders" asp-action="Edit" asp-route-id="@item.Id">Edit  |</a> <a asp-controller="orders" asp-action=" Delete" asp-route-id="@item.Id">Delete   |</a>
                    <a asp-controller="orders" asp-action="Details" asp-route-id="@item.Id">Order Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Unit4/Views/books/orderdetails.cshtml
@model IEnumerable<Unit4.Models.orderdetail>

@{
    ViewData["Title"] = "orderdetails";
}

<h1>orderdetails</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.booktitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.customer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.booktitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>